/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppCallScreenRouteImport } from './routes/_app.call-screen'
import { Route as AppCompaniesRouteImport } from './routes/_app.companies'
import { Route as AppDailyLeadsRouteImport } from './routes/_app.daily-leads'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDiaryRouteImport } from './routes/_app.diary'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppFoldersRouteImport } from './routes/_app.folders'
import { Route as AppFollowUpsRouteImport } from './routes/_app.follow-ups'
import { Route as AppInterestedRouteImport } from './routes/_app.interested'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppMonitoringRouteImport } from './routes/_app.monitoring'
import { Route as AppMyLeadsRouteImport } from './routes/_app.my-leads'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppLeadLeadIdRouteImport } from './routes/_app.lead.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppCallScreenRoute = AppCallScreenRouteImport.update({
  id: '/call-screen',
  path: '/call-screen',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyLeadsRoute = AppDailyLeadsRouteImport.update({
  id: '/daily-leads',
  path: '/daily-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDiaryRoute = AppDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppFoldersRoute = AppFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppInterestedRoute = AppInterestedRouteImport.update({
  id: '/interested',
  path: '/interested',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppMyLeadsRoute = AppMyLeadsRouteImport.update({
  id: '/my-leads',
  path: '/my-leads',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadLeadIdRoute = AppLeadLeadIdRouteImport.update({
  id: '/lead/$leadId',
  path: '/lead/$leadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AppAgentsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/attendance': typeof AppAttendanceRoute
  '/call-screen': typeof AppCallScreenRoute
  '/companies': typeof AppCompaniesRoute
  '/daily-leads': typeof AppDailyLeadsRoute
  '/dashboard': typeof AppDashboardRoute
  '/diary': typeof AppDiaryRoute
  '/employees': typeof AppEmployeesRoute
  '/folders': typeof AppFoldersRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/interested': typeof AppInterestedRoute
  '/leads': typeof AppLeadsRoute
  '/monitoring': typeof AppMonitoringRoute
  '/my-leads': typeof AppMyLeadsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/lead/$leadId': typeof AppLeadLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AppAgentsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/attendance': typeof AppAttendanceRoute
  '/call-screen': typeof AppCallScreenRoute
  '/companies': typeof AppCompaniesRoute
  '/daily-leads': typeof AppDailyLeadsRoute
  '/dashboard': typeof AppDashboardRoute
  '/diary': typeof AppDiaryRoute
  '/employees': typeof AppEmployeesRoute
  '/folders': typeof AppFoldersRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/interested': typeof AppInterestedRoute
  '/leads': typeof AppLeadsRoute
  '/monitoring': typeof AppMonitoringRoute
  '/my-leads': typeof AppMyLeadsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/lead/$leadId': typeof AppLeadLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/agents': typeof AppAgentsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/call-screen': typeof AppCallScreenRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/daily-leads': typeof AppDailyLeadsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diary': typeof AppDiaryRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/folders': typeof AppFoldersRoute
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/interested': typeof AppInterestedRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/my-leads': typeof AppMyLeadsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/lead/$leadId': typeof AppLeadLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/attendance'
    | '/call-screen'
    | '/companies'
    | '/daily-leads'
    | '/dashboard'
    | '/diary'
    | '/employees'
    | '/folders'
    | '/follow-ups'
    | '/interested'
    | '/leads'
    | '/monitoring'
    | '/my-leads'
    | '/notifications'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/tasks'
    | '/lead/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/attendance'
    | '/call-screen'
    | '/companies'
    | '/daily-leads'
    | '/dashboard'
    | '/diary'
    | '/employees'
    | '/folders'
    | '/follow-ups'
    | '/interested'
    | '/leads'
    | '/monitoring'
    | '/my-leads'
    | '/notifications'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/tasks'
    | '/lead/$leadId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/agents'
    | '/_app/analytics'
    | '/_app/attendance'
    | '/_app/call-screen'
    | '/_app/companies'
    | '/_app/daily-leads'
    | '/_app/dashboard'
    | '/_app/diary'
    | '/_app/employees'
    | '/_app/folders'
    | '/_app/follow-ups'
    | '/_app/interested'
    | '/_app/leads'
    | '/_app/monitoring'
    | '/_app/my-leads'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/lead/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-screen': {
      id: '/_app/call-screen'
      path: '/call-screen'
      fullPath: '/call-screen'
      preLoaderRoute: typeof AppCallScreenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-leads': {
      id: '/_app/daily-leads'
      path: '/daily-leads'
      fullPath: '/daily-leads'
      preLoaderRoute: typeof AppDailyLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diary': {
      id: '/_app/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AppDiaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/folders': {
      id: '/_app/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AppFoldersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interested': {
      id: '/_app/interested'
      path: '/interested'
      fullPath: '/interested'
      preLoaderRoute: typeof AppInterestedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-leads': {
      id: '/_app/my-leads'
      path: '/my-leads'
      fullPath: '/my-leads'
      preLoaderRoute: typeof AppMyLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead/$leadId': {
      id: '/_app/lead/$leadId'
      path: '/lead/$leadId'
      fullPath: '/lead/$leadId'
      preLoaderRoute: typeof AppLeadLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCallScreenRoute: typeof AppCallScreenRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppDailyLeadsRoute: typeof AppDailyLeadsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiaryRoute: typeof AppDiaryRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppFoldersRoute: typeof AppFoldersRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppInterestedRoute: typeof AppInterestedRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppMyLeadsRoute: typeof AppMyLeadsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppLeadLeadIdRoute: typeof AppLeadLeadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCallScreenRoute: AppCallScreenRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppDailyLeadsRoute: AppDailyLeadsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiaryRoute: AppDiaryRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppFoldersRoute: AppFoldersRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppInterestedRoute: AppInterestedRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppMyLeadsRoute: AppMyLeadsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppLeadLeadIdRoute: AppLeadLeadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
